# SPRING
spring:
  security:
    oauth2:
      client:
        provider:
          uaa:
            token-uri: http://uaa/oauth/token
        registration:
          uaa:
            client-id: internal
            client-secret: internal
            authorization-grant-type: client_credentials

# EUREKA
eureka:
  client:
    fetch-registry: true
